### ISSUE TITLE
Create welcome and log in pages from scratch

### ISSUE THREAD

**Issue by elenappuga** [Arquisoft/dechat_es4a#23]

**Comment by raibove** [comment]
can I contribute to the code.

**Comment by elenappuga** [comment]
> can I contribute to the code.

Hello, im sorry but this is a university project so we cannot count with external contributions, hope you can join us in future private projects!

**Comment by Lisa159** [comment]
In my branch there is a new angular project with a basic welcome and login page.
I will edited for our chat app.
